/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "manual_open.h"
#include "manual_open_aliases.h"
#include "digital_control.h"
#include "digital_control_aliases.h"
#include "manual_close.h"
#include "manual_close_aliases.h"
#include "start_pulse.h"
#include "HS_Clock.h"
#include "red.h"
#include "red_aliases.h"
#include "green.h"
#include "green_aliases.h"
#include "microsecond_clock.h"
#include "open_ind.h"
#include "open_ind_aliases.h"
#include "en_24.h"
#include "en_24_aliases.h"
#include "en_5.h"
#include "en_5_aliases.h"
#include "Bootloadable_1.h"
#include "Timer_1.h"
#include "Interrupt_Out.h"
#include "Interrupt_Out_aliases.h"
#include "microsecond_clock_1.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

